sudo: false

language: go
go:
  - 1.8

before_install:
  - go get -u github.com/FiloSottile/gvt
  - go get github.com/mitchellh/gox
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - gvt restore
  - make ci

after_success:
  - gox -os "linux darwin" -arch "386 amd64" -output "dist/kage-{{.OS}}_{{.Arch}}_{{.Dir}}" ./cmd/stats/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dist/*
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false