sudo: false

language: go
go:
  - 1.8

env:
  global:
  - REPO=msales/kage

services:
  - docker

before_install:
  - go get -u github.com/FiloSottile/gvt
  - go get github.com/mitchellh/gox
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - gvt restore
  - make ci
  - make docker
  - $HOME/gopath/bin/goveralls -service=travis-ci

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export BRANCH=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - if [ "$TRAVIS_TAG" != "" ]; then docker tag kage:latest $REPO:$TRAVIS_TAG; fi
  - docker tag kage:latest $REPO:$BRANCH
  - docker push $REPO

before_deploy:
  - gox -os "linux darwin" -arch "386 amd64" -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}" ./cmd/kage/

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false